# Generated by Django 5.1.2 on 2024-10-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_post", "0001_initial"),
        ("core_user", "0003_alter_user_created_alter_user_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="posts_liked",
            field=models.ManyToManyField(related_name="liked_by", to="core_post.post"),
        ),
    ]
