name: Build, Test and Deploy Postagram backend

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Injecting environment vars
      run: |
        echo "${{ secrets.TEST_SECRETS }}" >> .env
    - name: Building Docker containers
      run: |
        docker-compose up -d --build
        docker-compose logs
    - name: Running Tests inside Docker containers
      run: |
        docker-compose exec -T api pytest