name: Build, Test Postagram backend

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Injecting environment vars
      run: |
        echo "${{ secrets.TEST_SECRETS }}" >> .env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep tag_name | cut -d '"' -f 4)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Clean Up Old Containers
      run: |
        docker-compose down -v --remove-orphans
        docker builder prune -f

    - name: Building Docker containers
      run: |
        docker-compose up -d --build
        docker-compose logs
      env:
        # Ensure containers use a limited amount of resources
        COMPOSE_CONVERT_WINDOWS_PATHS: 1  # For compatibility if using Windows paths
        COMPOSE_PARALLEL_LIMIT: 2         # Limit parallelism to avoid excessive resource use

    - name: Running Tests inside Docker containers
      run: |
        docker-compose up -d --build --force-recreate --pull always
        docker-compose exec -T api pytest core/auth/tests.py

    # Set up CodeQL for code analysis
    - name: Set up CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python

    # Perform code analysis with CodeQL and limit RAM to prevent memory issues
    - name: Analyze with CodeQL
      run: |
        codeql database analyze db-python --ram=2048 --format=sarif -o results.sarif


    - name: Notify on Failure
      if: failure()
      uses: actions/github-script@v7  # Update if a new version is released
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          core.setOutput('summary', 'Build failed. Please check the logs.')
          core.setOutput('log-link', `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`)
