name: Build, Test Postagram backend

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Injecting environment vars
      run: |
        echo "${{ secrets.TEST_SECRETS }}" >> .env
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    - name: Building Docker containers
      run: |
        docker-compose up -d --build --force-recreate
        docker-compose exec -T api pytest -n auto  # Parallel test execution

    - name: Notify on Failure
      if: failure()
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          core.summary.add('Build failed. Please check the logs.')
          core.summary.add(`You can find the logs here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`)