name: Build, Test Postagram backend

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Injecting environment vars
      run: |
        echo "${{ secrets.TEST_SECRETS }}" >> .env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep tag_name | cut -d '"' -f 4)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Clean Up Old Containers
      run: |
        docker-compose down -v --remove-orphans
        docker builder prune -f

    - name: Building Docker containers
      run: |
        docker-compose up -d --build --force-recreate --pull always
        docker-compose logs

    - name: Running Tests inside Docker containers
      run: |
        docker-compose exec -T api pytest -n auto  # Parallel test execution

    - name: Notify on Failure
      if: failure()
      uses: actions/github-script@v7  # Update if a new version is released
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          core.setOutput('summary', 'Build failed. Please check the logs.')
          core.setOutput('log-link', `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`)