name: Build, Test Postagram backend

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Injecting environment vars
      run: |
        echo "${{ secrets.TEST_SECRETS }}" >> .env

    - name: Set up Docker Buildx
      uses: ./actions/setup-buildx-action

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Clean Up Old Containers
      run: |
        docker-compose down -v --remove-orphans
        docker builder prune -f

    - name: Building Docker containers
      run: |
        docker-compose up -d --build
        docker-compose logs

    - name: Running Tests inside Docker containers
      run: |
        docker-compose up -d --build --force-recreate --pull always
        docker-compose exec -T api pytest core/auth/tests.py

    - name: Notify on Failure
      if: failure()
      uses: actions/github-script@v7  # Update if a new version is released
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          core.setOutput('summary', 'Build failed. Please check the logs.')
          core.setOutput('log-link', `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`)
