name: Build and deploy frontend

on:
  push:
    branches: [ main ]

jobs:
 build-test-deploy:
   name: Tests
   runs-on: ubuntu-latest
   defaults:
     run:
       working-directory: ./social-media-app
   steps:
    - uses: actions/checkout@v4

    - name: Injecting environment variables
      run: echo "REACT_APP_API_URL=${{ secrets.API_URL }}" >> .env

    - name: Install dependencies
      run: yarn install

    - name: Running Tests
      run: yarn test

    - name: Building project
      run: yarn build

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to AWS S3 bucket
      run: aws s3 sync ./build/ s3://postagram-s3-bucket --delete